package model

// Example:
// "tableIndexConfig": {
// 	"rangeIndexVersion": 2,
// 	"autoGeneratedInvertedIndex": false,
// 	"createInvertedIndexDuringSegmentGeneration": false,
// 	"loadMode": "MMAP",
// 	"enableDefaultStarTree": false,
// 	"starTreeIndexConfigs": [
// 	  {
// 		"dimensionsSplitOrder": [
// 		  "AirlineID",
// 		  "Origin",
// 		  "Dest"
// 		],
// 		"functionColumnPairs": [
// 		  "COUNT__*",
// 		  "MAX__ArrDelay"
// 		],
// 		"maxLeafRecords": 10
// 	  }
// 	],
// 	"tierOverwrites": {
// 	  "hotTier": {
// 		"starTreeIndexConfigs": [
// 		  {
// 			"dimensionsSplitOrder": [
// 			  "Carrier",
// 			  "CancellationCode",
// 			  "Origin",
// 			  "Dest"
// 			],
// 			"skipStarNodeCreationForDimensions": [],
// 			"functionColumnPairs": [
// 			  "MAX__CarrierDelay",
// 			  "AVG__CarrierDelay"
// 			],
// 			"maxLeafRecords": 10
// 		  }
// 		]
// 	  },
// 	  "coldTier": {
// 		"starTreeIndexConfigs": []
// 	  }
// 	},
// 	"enableDynamicStarTreeCreation": true,
// 	"aggregateMetrics": false,
// 	"nullHandlingEnabled": false,
// 	"columnMajorSegmentBuilderEnabled": false,
// 	"optimizeDictionary": false,
// 	"optimizeDictionaryForMetrics": false,
// 	"noDictionarySizeRatioThreshold": 0.85
//   }

type TableIndexConfig struct {
}
